spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
mybatis-plus:
  mapper-locations: classpath*:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false
  global-config:
    db-config:
      update-strategy: ignored
      logic-delete-value: 1
      logic-not-delete-value: 0