server:
  port: 8083
spring:
  application:
    name: momp-menu
#  shardingsphere:
#    datasource:
#      names: ds0,ds1, ds2
#      ds0:
#        type: com.zaxxer.hikari.HikariDataSource
#        driver-class-name: com.mysql.cj.jdbc.Driver
#        url: jdbc:mysql://127.0.0.1:3306/momp?useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&serverTimezone=UTC
#        username: root
#        password: mysql
#      ds1:
#        type: com.zaxxer.hikari.HikariDataSource
#        driver-class-name: com.mysql.cj.jdbc.Driver
#        url: jdbc:mysql://127.0.0.1:3306/momp1?useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&serverTimezone=UTC
#        username: root
#        password: mysql
#      ds2:
#        type: com.zaxxer.hikari.HikariDataSource
#        driver-class-name: com.mysql.cj.jdbc.Driver
#        url: jdbc:mysql://127.0.0.1:3306/momp2?useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&serverTimezone=UTC
#        username: root
#        password: mysql
#    sharding:
#      default-data-source-name: ds0
#      tables:
#        menu:
#          actual-data-nodes: ds->{0..2}.menu->{0..2}
#          database-strategy:
#            inline:
#              sharding-column: id
#              algorithm-expression: ds$->{parent_id % 3}
#          table-strategy:
#            inline:
#              sharding-column: id
#              algorithm-expression: o_order$->{id % 3}
